apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: team6-cluster
  namespace: team6
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  kafka:
    config:
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      plain:
        authentiation:
          type: scram-sha-512
      tls:
        authentiation:
          type: tls
      external:
        type: route
        authentication:
          type: tls 
    replicas: 3
    storage:
      size: 5G
      type: persistent-claim
    version: 2.5.0
  zookeeper:
    replicas: 3
    storage:
      size: 5G
      type: persistent-claim