apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch
  namespace: openshift-operators
spec:
  channel: "4.6"
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace