---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker
  namespace: team6
spec:
  channel: current
  installPlanApproval: Automatic
  name: amq-broker
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq-broker-operator.v0.17.0