apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemis
metadata:
  name: team5-amq-broker
  namespace: team5
spec:
  acceptors:
    - expose: true
      name: amqp
      port: 5672
      protocols: 'true'
    - expose: true
      name: openwire
      port: 61616
      protocols: 'true'
  addressSettings:
    addressSetting:
      - autoCreateAddresses: true
        autoCreateDeadLetterResources: true
  console:
    expose: true
  deploymentPlan:
    image: >-
      registry.redhat.io/amq7/amq-broker@sha256:90ddd06465516fdf22e66e5f0b78d85b7727064f5879a009c23ebcfcc4ca321f
    journalType: nio
    messageMigration: false
    persistenceEnabled: true
    requireLogin: false
    size: 2